package com.example.dinehero;

import android.content.Intent;
import android.graphics.drawable.Drawable;
import android.os.Bundle;
import android.view.MenuItem;
import android.widget.Toast;

import androidx.annotation.ColorInt;
import androidx.annotation.NonNull;
import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.GridLayoutManager;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import com.example.dinehero.databinding.ActivityMainBinding;
import com.google.android.material.bottomnavigation.BottomNavigationView;
import com.google.android.material.navigation.NavigationBarView;

import java.util.ArrayList;

public class MainActivity2 extends AppCompatActivity {

    private RecyclerView products;
    private static ArrayList<Product> productsList = new ArrayList<>();
    private BottomNavigationView TNV;



     ActivityMainBinding binding;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);


        products = findViewById(R.id.Products);

        TNV = findViewById(R.id.topNavView);
        TNV.setItemActiveIndicatorEnabled(false);

        //Top Navigation View - Allows User to navigate through app.   Java File
        TNV.setOnItemSelectedListener(new NavigationBarView.OnItemSelectedListener() {
            @Override
            public boolean onNavigationItemSelected(@NonNull MenuItem item) {
                if (item.getItemId() == findViewById(R.id.btnDiscover).getId()) {
                    openCalenderActivity();

                } else if (item.getItemId() == findViewById(R.id.btnForYou).getId()) {
                    openForYouActivity();
                } else if (item.getItemId() == findViewById(R.id.btnFollowing).getId()) {
                    openProfileActivity();
                }
                else if (item.getItemId() == findViewById(R.id.btnSearch).getId()) {
                    openMainActivity();
                }

                return false;
            }
        });







        if(ForYouActivity.getFirst()) {


            //Events are called Products. This code allows all events to be displayed in the Event Page

            productsList.add(new Product("Community Picnic", "Hey, let's soak up the sun and enjoy some good food and even better company! Imagine spreading out a cozy blanket in a lush park or by a sparkling lake, surrounded by nature's beauty. We'll share delicious snacks, laughter, and maybe even a game or two. It's the perfect opportunity to catch up, unwind, and create lasting memories together. So grab your favorite snacks, a comfy blanket, and join me for a relaxing picnic in the great outdoors. Trust me, it's going to be a day to remember!", "Orange Park", new User("MacyKenner", "ihbshb@",R.drawable.women,32,4.2,"\uD83C\uDF1F Entrepreneur by day, dreamer by night! \uD83D\uDE80 Founder of a boutique marketing agency with a side hustle in spreading smiles and good vibes. Chicago born and raised, so you know I've got that Midwestern charm! \uD83D\uDE0A Passionate about shaking up the status quo and making a positive impact. \uD83D\uDCBC When I'm not hustling, you can find me exploring the city's hidden gems or binge-watching my favorite sitcoms. \uD83C\uDFD9️ Firm believer in the power of community and lifting each other up. \uD83C\uDF08 Let's chat about business, social change, or our latest Netflix obsessions! Oh, and did I mention I make killer homemade cookies? 405-567-9847",5), R.drawable.picnic,false,"07/05/24",2,4,0));
            productsList.add(new Product("Biking Trail","Calling all adventurers! Who's up for an exhilarating bike ride through scenic trails and winding paths? Picture the wind in your hair, the thrill of speeding down hills, and the sense of freedom that comes with every pedal. Whether you're a seasoned cyclist or a newbie, biking with friends adds an extra layer of fun and camaraderie. So grab your helmet, hop on your bike, and let's explore the great outdoors together. Trust me, it's going to be an adventure you won't forget!","Lake Eola",new User("TrentWilliams","asdfghjkl;",R.drawable.men2,26,4.5,"\uD83C\uDFB8 Musician with a day job as a software engineer - talk about a double life! \uD83C\uDFB6 Strumming chords by night, coding by day. \uD83D\uDDA5️ Proud West Coaster soaking up the sun and surfing whenever I can catch a wave. \uD83C\uDFC4\u200D♂️ When I'm not lost in lines of code or jamming with my band, you can find me exploring the great outdoors or chilling with my furry best friend, Max. \uD83D\uDC3E Passionate about technology, music, and finding the perfect taco spot. \uD83C\uDF2E Let's swap Spotify playlists or geek out over the latest tech trends! \uD83E\uDD18 #TechieRockstar #SurferDude #TacoEnthusiast 405-875-9632",2),R.drawable.bike, false, "05/18/24",3,10,5));
            productsList.add(new Product("Swimming & Fun", "Hey there, water enthusiasts! Let's make a splash and cool off from the summer heat with a refreshing swim. Picture diving into crystal-clear waters, feeling weightless and carefree as you swim laps or simply float under the sun. Whether it's at a local pool, a tranquil lake, or the crashing waves of the ocean, swimming with friends is always a blast. So grab your swimsuit, sunscreen, and towel, and let's dive into some aquatic fun together. Trust me, it's going to be a day filled with laughter, sunshine, and unforgettable memories!", "Lake Eola", new User("RebeccaRoberts","qwertyui",R.drawable.women2,31,4.2,"\uD83D\uDCDA Bookworm with a love for storytelling and a passion for adventure. \uD83C\uDF1F Whether it's getting lost in the pages of a fantasy novel or exploring new worlds through travel, I'm always seeking out new tales to inspire my own adventures. \uD83C\uDF0D Proud explorer of both distant lands and the depths of imagination. \uD83D\uDDFA️ When I'm not lost in a good book or planning my next getaway, you can find me indulging in my love for photography or baking up a storm in the kitchen. \uD83D\uDCF8\uD83C\uDF70 Firm believer in the power of kindness and spreading joy wherever I go. Let's swap book recommendations or share stories from our own travels! 405-852-9638",3),R.drawable.swin,false,"06/17/24",1,6,0 ));
            productsList.add(new Product("Food Bank","Welcome to our Food Bank Event, where compassion and generosity flourish. Here, we're not just serving meals; we're offering hope to those facing hunger in our community. From the moment you step in, immerse yourself in a spirit of unity and purpose. Let your taste buds embark on a unique culinary journey crafted by our local chefs using ingredients from the food bank, each bite symbolizing solidarity and support. But it's more than just food; it's about fostering connections and building a stronger community. Engage in heartfelt conversations, share stories, and forge meaningful bonds. Together, we can amplify our impact and create lasting change. Join us for a day filled with heartwarming moments, delectable dishes, and the knowledge that each plate served brings us closer together","Pensacola Food Bank",new User("JasonBlake","volunteer123",R.drawable.men14,43,4.9,"\uD83C\uDF31 Environmentalist with a passion for protecting our planet and advocating for sustainability. \uD83C\uDF0D Whether it's organizing a beach cleanup or planting trees, I'm always chasing the perfect eco-friendly solution. \uD83C\uDF3F Rooted in a deep love for nature, I find inspiration in the beauty of our natural world. \uD83C\uDF3B When I'm not leading environmental initiatives, you can find me tending to my garden, exploring local farmer's markets, or practicing mindfulness in the great outdoors. \uD83D\uDC36 Proud dog parent to Barkley, the most adventurous eco-warrior you'll ever meet! \uD83D\uDC3E Let's share green living tips or plan our next volunteer project. \uD83C\uDF31 #EarthProtector #Gardener #OutdoorEnthusiast 405-999-8659",4),R.drawable.foodbank,false,"08/10/24",7,15,0));
            productsList.add(new Product("Camping Trip","Hey, nature lovers! How about we escape the hustle and bustle of the city and spend a night under the stars? Imagine gathering around a crackling campfire, roasting marshmallows, and sharing stories late into the night. With the sounds of nature as our soundtrack, we'll fall asleep under a blanket of stars, feeling refreshed and rejuvenated by the great outdoors. Whether you're a seasoned camper or new to the experience, camping with friends is always an adventure to remember. So grab your tent, sleeping bag, and sense of adventure, and let's embark on a camping trip we'll never forget. Trust me, it's going to be an unforgettable journey filled with laughter, friendship, and the beauty of nature!","Orlando Camp Grounds",new User("EthanAllen","zxcvbn",R.drawable.men3,47,4.1,"\uD83C\uDFA8 Creative soul with a flair for design and a knack for DIY projects. \uD83D\uDD8C️ Whether it's refurbishing old furniture or sketching out new home decor ideas, I'm always on a mission to bring beauty into everyday life. \uD83D\uDCA1 Proud small-town guy with big city dreams. \uD83C\uDF06 When I'm not busy crafting or brainstorming my next project, you can catch me sipping on artisanal coffee or browsing through flea markets in search of hidden treasures. ☕ Thrilled to be a part of the maker community and constantly inspired by fellow artists and craftsmen. Let's chat about all things design, from mid-century modern to rustic chic! 405-753-4158",4),R.drawable.camp,false,"08/02/24",2,3,10));
            productsList.add(new Product("Brisket BBQ","Let's fire up the grill and indulge in a mouthwatering barbecue feast! Picture sizzling burgers, juicy steaks, and perfectly grilled veggies, all enjoyed in the company of good friends. With the aroma of delicious food filling the air and the sound of laughter echoing around us, a barbecue gathering promises to be a flavorful and fun-filled event. So grab your apron, your favorite marinades, and join me for a grill-out extravaganza that's sure to satisfy your taste buds and lift your spirits!","1900 Caywood Rd",new User("ZackTurner","kjhgfds",R.drawable.men4,25,3.9,"\uD83C\uDFAE Gamer by night, tech wizard by day! \uD83D\uDCBB Whether I'm diving into the latest RPG or coding up a storm, I'm always in my element when I'm immersed in the world of technology. \uD83D\uDE80 Proud nerd with a passion for all things sci-fi and fantasy. \uD83C\uDF0C When I'm not conquering virtual realms or tinkering with gadgets, you can find me exploring the great outdoors or whipping up some mean BBQ on the grill. \uD83C\uDF54\uD83D\uDD25 Firm believer in the power of friendship and the importance of always having a backup plan. Let's geek out over our favorite games or debate the merits of Star Trek vs. Star Wars! 405-547-1563",6),R.drawable.bbbbbbqqq,false,"08/12/24",9,15,5));
            productsList.add(new Product("Art Class","Welcome to our Art Class, where creativity flows freely and imaginations ignite. Step into our vibrant studio space, where every stroke of the brush and swirl of color is an expression of individuality and inspiration. From the moment you enter, you'll feel the embrace of our artistic community, united in our passion for self-expression and exploration. Dive into a world of possibility as you unleash your creativity on canvas or paper, guided by our skilled instructors who nurture each student's unique talents. Whether you're a seasoned artist or a beginner, there's a place for you here to discover, learn, and grow. But our Art Class Oasis is more than just a place to create; it's a sanctuary of self-discovery and connection. Take a seat at our communal table of creativity and engage in conversations that spark new ideas and perspectives.","ArtBasics",new User("SeanHulsey","art123",R.drawable.men12,28,4.9,"\uD83C\uDFA8 Artist with a passion for capturing emotions on canvas. \uD83C\uDF1F Whether it's a poignant portrait or a vibrant abstract, I'm always chasing the perfect expression. \uD83C\uDFDE️ Inspired by the beauty of nature, I find solace and inspiration in the great outdoors. \uD83D\uDD8C️ When I'm not painting, you can find me sketching, hiking, or savoring a cup of aromatic coffee. \uD83D\uDC3E Proud cat parent to Mochi, the most mischievous muse you'll ever meet! \uD83C\uDFA8 Let's share artistic inspiration or plan our next gallery visit. \uD83D\uDE0A #ArtisticSoul #CatParent #NatureLover 405-875-8879",2),R.drawable.art,false,"09/29/24",4,5,8));
            productsList.add(new Product("ACT Prep","Welcome to our ACT Prep, the ultimate destination for students striving for academic excellence. As you step into our dynamic learning environment, you'll find a dedicated team of instructors ready to guide you through comprehensive study sessions tailored to your individual needs. From mastering test-taking strategies to conquering challenging subjects, our goal is to equip you with the skills and confidence needed to excel on the ACT. But beyond just preparing for the test, our hub fosters a supportive community of learners, where collaborative study sessions and engaging discussions enrich the learning experience. Join us as we embark on this journey together, empowering you to reach your full potential and achieve success on the ACT and beyond.","Sunshine Library",new User("MaxWalter","qwerty123",R.drawable.men9,26,4.7, "\uD83C\uDFAD Actor with a passion for embodying characters and bringing stories to life. \uD83C\uDFAC Whether it's a riveting drama or a hilarious comedy, I'm always chasing the perfect performance. \uD83C\uDFAD Immersed in the vibrant energy of the theater, I find inspiration in every stage I step onto. \uD83C\uDFA5 When I'm not rehearsing lines, you can find me exploring local cafes, attending live performances, or practicing yoga. \uD83C\uDF3F Proud plant parent to Fern, the most graceful green companion you'll ever meet! \uD83C\uDF3F Let's share acting tips or plan our next theater outing. \uD83C\uDFAD #DramaQueen #PlantParent #CoffeeLover 405-958-4100" ,6),R.drawable.act,false,"07/12/24",2,5,15));
            productsList.add(new Product("Group Run","Lace up your running shoes and join me for an energizing jog through scenic trails or bustling city streets. Feel the rhythm of your heartbeat syncing with the cadence of your footsteps as we push ourselves to new limits together. Whether it's a leisurely jog or a competitive race, running with friends adds motivation, encouragement, and a healthy dose of friendly competition. So let's hit the pavement, breathe in the fresh air, and experience the exhilaration of pounding the pavement side by side. Trust me, the endorphin rush and sense of accomplishment will make it all worth it!","Clearwater Downtown",new User("JuniorYombi","olmkubn",R.drawable.men5,22,4.9,"\uD83C\uDFA8 Artist with a passion for painting the world in vibrant colors. \uD83D\uDD8C️ Whether I'm creating captivating portraits or experimenting with abstract forms, I'm always on a journey to express myself through art. \uD83C\uDF1F Proud dreamer with a vision for a brighter, more beautiful world. \uD83C\uDF08 When I'm not lost in my creative process, you can find me exploring nature's wonders or jamming out to my favorite tunes on the guitar. \uD83C\uDFB6 Firm believer in the power of positivity and spreading love through my artwork. Let's swap artistic inspirations or embark on a spontaneous adventure to find the perfect painting spot! 405-864-9854",11),R.drawable.run,false,"07/03/24",4,5,0));
            productsList.add(new Product("Fishing","Calling all angling enthusiasts! Let's cast our lines and reel in some big catches together. Whether it's casting off from the shore of a tranquil lake, chartering a boat for deep-sea fishing, or fly-fishing in a rushing river, there's something truly special about fishing with friends. Feel the excitement as you wait for the telltale tug on your line, the anticipation building with each passing moment until finally, you hook your prize. With the sun shining above and the water shimmering below, it's the perfect setting for a day of relaxation, camaraderie, and maybe even a little friendly competition. So grab your fishing gear, bait your hooks, and join me for a fishing adventure that's sure to reel in some unforgettable memories!","Lake Florida",new User("LaneePhilip","yuioplkjhg",R.drawable.women3,52,5.0,"\uD83D\uDCF8 Photography enthusiast with a passion for capturing life's fleeting moments. \uD83C\uDF1F Whether I'm chasing sunsets or documenting candid smiles, I'm always on the lookout for beauty in the world around me. \uD83D\uDCF7 Proud explorer with a love for travel and a desire to see every corner of the globe. \uD83C\uDF0D When I'm not behind the lens, you can find me hiking through nature trails or immersing myself in a good book at a cozy café. \uD83D\uDCDA Firm believer in the power of connection and the ability of photographs to tell stories that transcend language barriers. Let's share our favorite travel destinations, swap photography tips, or embark on an adventure together! 405-965-8945",2),R.drawable.fish,false,"09/13/24",3,4,7));
            productsList.add(new Product("Birdwatching"," Let's spread our wings and embark on a serene journey into the world of avian wonders! Whether we're exploring lush forests, tranquil wetlands, or scenic coastal areas, there's always something fascinating to discover in the realm of birdwatching. With binoculars in hand and field guides at the ready, we'll seek out feathered friends of all shapes, sizes, and colors, from majestic raptors soaring overhead to delicate songbirds hidden among the branches. As we quietly observe their behaviors and listen to their melodic calls, we'll gain a deeper appreciation for the beauty and diversity of the natural world. So let's wander off the beaten path, follow the flutter of wings, and immerse ourselves in the captivating world of birdsong and flight.","Destin Nature Park",new User("JeffSulk","qhdjskdn",R.drawable.men7,23,4.6,"\uD83C\uDFB5 Music aficionado with a groove for every beat and a melody for every mood. \uD83C\uDFB6 Whether I'm spinning vinyl at a local club or jamming out on my guitar at home, I'm always immersed in the rhythm of life. \uD83C\uDFB8 Proud audiophile with a collection that spans genres and decades. \uD83D\uDCC0 When I'm not lost in the world of music, you can find me exploring the city's vibrant music scene or seeking out the perfect cup of coffee to fuel my next jam session. ☕ Firm believer in the power of music to heal, inspire, and unite. Let's swap playlists, share concert stories, or maybe even start a band together! 405-875-7412",3),R.drawable.bird,false,"05/18/24",1,3,0));
            productsList.add(new Product("Bowling"," Let's lace up our bowling shoes and roll our way to strike after strike in a fun-filled game of bowling with friends! Whether it's the satisfying sound of pins crashing or the friendly competition among teammates, there's nothing quite like the excitement of bowling alley camaraderie. With each toss of the ball, we'll aim for the perfect score while sharing laughs, high-fives, and maybe even a victory dance or two. So let's gather our crew, pick out our favorite balls, and hit the lanes for an unforgettable night of strikes, spares, and endless fun. Trust me, whether you're a seasoned bowler or a first-timer, the thrill of knocking down pins with friends is an experience that's sure to be a strike!","MainEvent",new User("PeterRick","poiuhnm",R.drawable.men8,38,4.7,"\uD83D\uDE80 Tech enthusiast with a passion for innovation and a knack for problem-solving. \uD83D\uDCA1 Whether I'm coding late into the night or brainstorming the next big idea, I'm always on the cutting edge of technology. \uD83D\uDDA5️ Proud geek with a love for all things sci-fi and a collection of gadgets that would make even Tony Stark jealous. \uD83C\uDF0C When I'm not immersed in the digital realm, you can find me exploring the great outdoors or whipping up some delicious dishes in the kitchen. \uD83C\uDF73 Firm believer in the power of technology to shape a better future and make the impossible possible. Let's chat about the latest tech trends, swap coding tips, or plan our next intergalactic adventure! 405-2358-9865",2),R.drawable.bowl,false,"07/12/24",2,7,10));
            productsList.add(new Product("Cornhole Toss", " Let's grab some bean bags and challenge each other to a friendly game of cornhole in the great outdoors! Whether it's a backyard barbecue, a beachside bonfire, or a tailgate party before the big game, cornhole is the perfect addition to any gathering. With each toss of the bag, we'll aim for the elusive hole while soaking in the sunshine and enjoying the company of friends. With cheers and jeers ringing out with each toss, the friendly competition will keep us on our toes and the laughter flowing. So let's set up the boards, mark our throwing lines, and let the games begin! Trust me, a day of cornhole with friends is a recipe for endless entertainment, friendly rivalry, and memories that will last a lifetime.","2114 Newberry Ave",new User("AveryMedows","asedrfrf",R.drawable.women4,27,4.3,"\uD83C\uDFA8 Creative soul with a passion for expressing myself through art in all its forms. \uD83C\uDF1F Whether I'm painting on canvas, crafting pottery, or strumming chords on my guitar, I'm always seeking new ways to bring beauty into the world. \uD83D\uDD8C️ Proud dreamer with a love for exploring the depths of imagination and pushing the boundaries of creativity. \uD83C\uDF0C When I'm not lost in my creative pursuits, you can find me exploring nature's wonders, indulging in a good book, or savoring a cup of coffee at a cozy café. ☕ Firm believer in the power of art to inspire, heal, and connect us all. Let's swap artistic inspirations, share our favorite books, or maybe even collaborate on a project together! 405-847-8569",4),R.drawable.corn,false,"08/02/24",1,6,0));
            productsList.add(new Product("Country Tailgate"," Let's rev up the excitement and turn the parking lot into our own pre-game party zone with a tailgate extravaganza! Whether we're gearing up for a sports showdown, a concert, or simply celebrating the joy of being together, there's no better way to kick off the festivities than with a tailgate with friends. From firing up the grill to setting up lawn games and cranking up the tunes, we'll create an atmosphere of fun, food, and camaraderie that sets the stage for an unforgettable day. With the aroma of barbecue filling the air, the sound of laughter and cheers echoing around us, and the anticipation of the main event building with each passing moment, a tailgate with friends is more than just a prelude – it's a celebration in its own right. So let's break out the coolers, deck out our vehicles, and get ready to party in style!","UM Stadium Parking",new User("PiperWoodard","poiuyhbnmjuygf",R.drawable.women5,19,4.8,"\uD83C\uDF3F Nature enthusiast with a heart full of wanderlust and a soul that craves adventure. \uD83C\uDF3B Whether I'm hiking through lush forests or camping under the stars, I'm always happiest when surrounded by the beauty of the great outdoors. \uD83C\uDFDE️ Proud environmentalist with a passion for sustainability and a love for all creatures big and small. \uD83E\uDD8B When I'm not exploring Mother Nature's wonders, you can find me curled up with a good book or experimenting with plant-based recipes in the kitchen. \uD83D\uDCDA\uD83E\uDD51 Firm believer in the power of connection and the importance of living in harmony with the Earth. Let's swap hiking stories, share tips for reducing our carbon footprint, or plan our next eco-friendly adventure! 405-852-9684",12),R.drawable.tail,false,"10/29/24",2,5,5));
            productsList.add(new Product("Hot Air Balloon","Experience the thrill of soaring high above the ground as you embark on an unforgettable journey in a hot air balloon. Step into the basket, feel the gentle breeze caress your skin, and marvel at the breathtaking views stretching out below you. As the balloon ascends, you'll witness the world from a new perspective, with panoramic vistas of rolling landscapes, sparkling lakes, and distant horizons unfolding before your eyes. Whether you're gliding serenely over picturesque countryside or floating gracefully above bustling cityscapes, the sense of freedom and tranquility is unparalleled. Soar with me, and let's chase the sunrise or sunset together, as we create memories that will last a lifetime.", "Tallahassee Air Field",new User("ZackTurner","kjhgfds",R.drawable.men4,25,3.9,"\uD83C\uDFAE Gamer by night, tech wizard by day! \uD83D\uDCBB Whether I'm diving into the latest RPG or coding up a storm, I'm always in my element when I'm immersed in the world of technology. \uD83D\uDE80 Proud nerd with a passion for all things sci-fi and fantasy. \uD83C\uDF0C When I'm not conquering virtual realms or tinkering with gadgets, you can find me exploring the great outdoors or whipping up some mean BBQ on the grill. \uD83C\uDF54\uD83D\uDD25 Firm believer in the power of friendship and the importance of always having a backup plan. Let's geek out over our favorite games or debate the merits of Star Trek vs. Star Wars! 405-8532-3245",6),R.drawable.hotbollon,false,"06/11/24",4,6,7));
            productsList.add(new Product("Jet Skiing","Rev up your adrenaline and feel the rush of speed as you navigate the waves on a jet ski adventure. Strap on your life jacket, rev the engine, and feel the spray of cool water against your face as you carve through the waves with skill and precision. Whether you're racing across open waters, performing daring stunts, or exploring hidden coves and secluded beaches, jet skiing offers an exhilarating blend of excitement and freedom. With the wind in your hair and the sun on your skin, every twist and turn of the throttle brings a surge of adrenaline and a sense of limitless possibility. So join me, and let's embark on an aquatic adventure that will leave us feeling alive and invigorated.","Miami Lake", new User("PeterRick","poiuhnm",R.drawable.men8,38,4.7,"\uD83D\uDE80 Tech enthusiast with a passion for innovation and a knack for problem-solving. \uD83D\uDCA1 Whether I'm coding late into the night or brainstorming the next big idea, I'm always on the cutting edge of technology. \uD83D\uDDA5️ Proud geek with a love for all things sci-fi and a collection of gadgets that would make even Tony Stark jealous. \uD83C\uDF0C When I'm not immersed in the digital realm, you can find me exploring the great outdoors or whipping up some delicious dishes in the kitchen. \uD83C\uDF73 Firm believer in the power of technology to shape a better future and make the impossible possible. Let's chat about the latest tech trends, swap coding tips, or plan our next intergalactic adventure! 405-897-6821",2),R.drawable.jetski,false,"09/27/24",2,3,0));
            productsList.add(new Product("Scuba Training","Dive into a world of wonder and discovery as you embark on a scuba training adventure. Slip into your wetsuit, adjust your mask and fins, and take a deep breath as you prepare to explore the mysterious depths below. Under the guidance of experienced instructors, you'll learn essential scuba diving skills, from buoyancy control to underwater navigation, as you gradually descend into the mesmerizing world beneath the surface. Encounter vibrant coral reefs teeming with life, graceful marine creatures gliding through the water, and hidden treasures waiting to be uncovered. With each dive, you'll gain confidence and mastery, unlocking new levels of exploration and excitement. So join me, and let's dive into an underwater paradise together, where every dive brings new discoveries and unforgettable experiences.","learningDepths",new User("AlexMiller","wsedrfttg",R.drawable.men6,24,3.2,"\uD83C\uDFAD Theatre enthusiast with a passion for bringing stories to life on stage. \uD83C\uDFAC Whether I'm treading the boards or behind the scenes, I'm always drawn to the magic of the spotlight. \uD83C\uDF1F Proud performer with a flair for drama and a heart full of passion. ❤️ When I'm not rehearsing lines or perfecting my craft, you can find me exploring the city's hidden gems or indulging in my love for good food and great company. \uD83C\uDF7D️ Firm believer in the power of storytelling to inspire, educate, and unite. Let's chat about our favorite plays, swap acting tips, or plan a night out at the theatre! 405-742-5556",5),R.drawable.scuba,false,"08/01/24",1,5,10));
            productsList.add(new Product("Flag Football","Feel the rush of adrenaline as you charge across the field in a fast-paced game of flag football. Lace up your cleats, grab your flag belt, and get ready to unleash your competitive spirit as you sprint, dodge, and dive to outmaneuver your opponents. With each pass and touchdown, you'll feel the thrill of victory and the camaraderie of teamwork, as you and your teammates work together to outsmart the defense and score points. Whether you're intercepting passes, juking past defenders, or diving for the end zone, flag football is an action-packed sport that combines strategy, skill, and sheer athleticism. Let's make some unforgettable memories as we battle it out on the field.","Homestead Soccer Field",new User("JarenGonzales", "ihbshb@",R.drawable.men,24,4.8,"\uD83D\uDCF8 Photographer with a passion for capturing life's beautiful moments. \uD83C\uDF1F Whether it's a breathtaking landscape or candid smiles, I'm always chasing the perfect shot. \uD83D\uDCF7 Born and raised in the city but happiest when I'm exploring the great outdoors. \uD83C\uDFDE️ When I'm not behind the lens, you can find me hiking, camping, or indulging in my love for spicy food. \uD83C\uDF36️ Proud dog dad to Luna, the fluffiest adventure buddy you'll ever meet! \uD83D\uDC3E Let's swap photography tips or plan our next spontaneous road trip. \uD83D\uDE0A #Wanderlust #DogDad #AdventureSeeker 405-996-2365",8),R.drawable.flagfootball,false,"07/03/24",9,16,5));
            productsList.add(new Product("Kids Soccer","Kick off your soccer shoes and join the excitement as kids take to the field in a thrilling game of soccer. From dribbling and passing to shooting and scoring, young players will hone their skills and showcase their talents as they compete against their peers in a friendly and supportive environment. With each goal and save, they'll experience the joy of teamwork and the thrill of victory, while also learning important lessons in sportsmanship and cooperation. Whether they're playing in a local league, a school tournament, or just kicking around with friends, kids soccer is a fun and rewarding way to stay active, build confidence, and make lifelong memories. So grab your cleats, gather your teammates, and get ready to kick up some fun on the field.","Homestead Soccer Field",new User("JarenGonzales", "ihbshb@",R.drawable.men,24,4.8,"\uD83D\uDCF8 Photographer with a passion for capturing life's beautiful moments. \uD83C\uDF1F Whether it's a breathtaking landscape or candid smiles, I'm always chasing the perfect shot. \uD83D\uDCF7 Born and raised in the city but happiest when I'm exploring the great outdoors. \uD83C\uDFDE️ When I'm not behind the lens, you can find me hiking, camping, or indulging in my love for spicy food. \uD83C\uDF36️ Proud dog dad to Luna, the fluffiest adventure buddy you'll ever meet! \uD83D\uDC3E Let's swap photography tips or plan our next spontaneous road trip. \uD83D\uDE0A #Wanderlust #DogDad #AdventureSeeker 405-895-6677",8),R.drawable.soccer,false,"07/04/24",4,16,5));
            productsList.add(new Product("Basketball","Get ready to hit the court and show off your skills in an electrifying game of basketball. Strap on your sneakers, dribble down the court, and feel the adrenaline pumping as you go head-to-head against your rivals in a fast-paced and fiercely competitive matchup. From three-pointers and slam dunks to steals and blocks, every play is an opportunity to showcase your talent and prove yourself as a true baller. Whether you're playing in a local league, a school tournament, or just shooting hoops with friends, teen basketball is a thrilling and dynamic sport that challenges players both mentally and physically. So lace up your shoes, grab your jersey, and get ready to ball out on the court.","Tampa Courts",new User("EthanAllen","zxcvbn",R.drawable.men3,47,4.1,"\uD83C\uDFA8 Creative soul with a flair for design and a knack for DIY projects. \uD83D\uDD8C️ Whether it's refurbishing old furniture or sketching out new home decor ideas, I'm always on a mission to bring beauty into everyday life. \uD83D\uDCA1 Proud small-town guy with big city dreams. \uD83C\uDF06 When I'm not busy crafting or brainstorming my next project, you can catch me sipping on artisanal coffee or browsing through flea markets in search of hidden treasures. ☕ Thrilled to be a part of the maker community and constantly inspired by fellow artists and craftsmen. Let's chat about all things design, from mid-century modern to rustic chic! 405-878-9986",4),R.drawable.basket,false,"07/11/24",3,6,0));
            productsList.add(new Product("Golf","Experience the tranquility and precision of golf as you step onto the lush green fairways of the course. Grab your clubs, feel the gentle breeze against your skin, and take a deep breath as you prepare to tee off on a memorable round of golf. With each swing and putt, you'll immerse yourself in the serene beauty of the landscape, surrounded by towering trees, sparkling water hazards, and manicured greens. Whether you're a seasoned pro or a novice player, golf offers a unique blend of skill, strategy, and relaxation, making it the perfect way to unwind and reconnect with nature. So join me on the links, and let's tee up for a day of unforgettable moments and endless enjoyment.","Hole 18's",new User("LaneePhilip","yuioplkjhg",R.drawable.women3,52,5.0,"\uD83D\uDCF8 Photography enthusiast with a passion for capturing life's fleeting moments. \uD83C\uDF1F Whether I'm chasing sunsets or documenting candid smiles, I'm always on the lookout for beauty in the world around me. \uD83D\uDCF7 Proud explorer with a love for travel and a desire to see every corner of the globe. \uD83C\uDF0D When I'm not behind the lens, you can find me hiking through nature trails or immersing myself in a good book at a cozy café. \uD83D\uDCDA Firm believer in the power of connection and the ability of photographs to tell stories that transcend language barriers. Let's share our favorite travel destinations, swap photography tips, or embark on an adventure together! 405-698-6321",2),R.drawable.golf,false,"11/02/24",1,4,0));
            productsList.add(new Product("Book Club","Escape into the captivating world of literature as you join a vibrant book club filled with fellow bibliophiles. Dust off your favorite novels, brew a cup of tea, and settle into a cozy chair as you delve into the pages of captivating stories and thought-provoking discussions. From classic literature to contemporary bestsellers, each book club meeting offers a chance to explore new perspectives, share insights, and connect with others who share your love of reading. Whether you're unraveling the mysteries of a thrilling mystery novel, dissecting the themes of a powerful work of fiction, or simply enjoying the camaraderie of fellow book lovers, book club is a welcoming and enriching experience that celebrates the joy of literature. So grab your reading glasses, open your mind, and get ready to embark on a literary journey like no other.","1487 Valencia ST",new User("LaneePhilip","yuioplkjhg",R.drawable.women3,52,5.0,"\uD83D\uDCF8 Photography enthusiast with a passion for capturing life's fleeting moments. \uD83C\uDF1F Whether I'm chasing sunsets or documenting candid smiles, I'm always on the lookout for beauty in the world around me. \uD83D\uDCF7 Proud explorer with a love for travel and a desire to see every corner of the globe. \uD83C\uDF0D When I'm not behind the lens, you can find me hiking through nature trails or immersing myself in a good book at a cozy café. \uD83D\uDCDA Firm believer in the power of connection and the ability of photographs to tell stories that transcend language barriers. Let's share our favorite travel destinations, swap photography tips, or embark on an adventure together! 405-865-9638",2),R.drawable.book,false,"07/15/24",7,9,0));
            productsList.add(new Product("Horse Riding","Saddle up and embark on an exhilarating adventure as you hit the trails for a horse riding excursion. Feel the gentle rhythm of your horse's hooves beneath you as you explore scenic landscapes, wooded trails, and open fields. Whether you're a seasoned equestrian or a first-time rider, horse riding offers a unique opportunity to connect with nature, bond with these majestic animals, and experience the thrill of freedom and exploration. From leisurely trail rides to exhilarating gallops, each ride brings a sense of serenity and excitement, as you forge a deeper connection with your equine companion and discover the beauty of the great outdoors. So grab your helmet, saddle up, and get ready to embark on a horse riding adventure that will leave you feeling invigorated, inspired, and truly alive.","BlueRay Ranch",new User("PiperWoodard","poiuyhbnmjuygf",R.drawable.women5,19,4.8,"\uD83C\uDF3F Nature enthusiast with a heart full of wanderlust and a soul that craves adventure. \uD83C\uDF3B Whether I'm hiking through lush forests or camping under the stars, I'm always happiest when surrounded by the beauty of the great outdoors. \uD83C\uDFDE️ Proud environmentalist with a passion for sustainability and a love for all creatures big and small. \uD83E\uDD8B When I'm not exploring Mother Nature's wonders, you can find me curled up with a good book or experimenting with plant-based recipes in the kitchen. \uD83D\uDCDA\uD83E\uDD51 Firm believer in the power of connection and the importance of living in harmony with the Earth. Let's swap hiking stories, share tips for reducing our carbon footprint, or plan our next eco-friendly adventure! 405-785-2514",12),R.drawable.horse,false,"08/29/24",4,5,0));
            productsList.add(new Product("Kayaking","Feel the rush of adrenaline as you embark on an exhilarating kayaking adventure. Grab your paddle, don your life jacket, and launch your kayak into the shimmering waters as you set off on a journey of exploration and excitement. Whether you're navigating gentle rivers, tranquil lakes, or thrilling whitewater rapids, kayaking offers a thrilling blend of adventure and tranquility. With each stroke of the paddle, you'll glide through breathtaking scenery, from towering cliffs and lush forests to hidden coves and pristine shorelines. Whether you're a seasoned paddler seeking an adrenaline-fueled challenge or a beginner looking for a peaceful escape, kayaking promises an unforgettable experience that will leave you feeling invigorated and inspired. So grab your paddle, embrace the rhythm of the water, and let the adventure begin!","Miami Lake",new User("PiperWoodard","poiuyhbnmjuygf",R.drawable.women5,19,4.8,"\uD83C\uDF3F Nature enthusiast with a heart full of wanderlust and a soul that craves adventure. \uD83C\uDF3B Whether I'm hiking through lush forests or camping under the stars, I'm always happiest when surrounded by the beauty of the great outdoors. \uD83C\uDFDE️ Proud environmentalist with a passion for sustainability and a love for all creatures big and small. \uD83E\uDD8B When I'm not exploring Mother Nature's wonders, you can find me curled up with a good book or experimenting with plant-based recipes in the kitchen. \uD83D\uDCDA\uD83E\uDD51 Firm believer in the power of connection and the importance of living in harmony with the Earth. Let's swap hiking stories, share tips for reducing our carbon footprint, or plan our next eco-friendly adventure! 405-321-6952",12),R.drawable.kyack,false,"07/14/24",3,7,0));
            productsList.add(new Product("Zip-lining","Soar through the treetops and experience the thrill of zip-lining as you embark on an unforgettable adventure high above the ground. Strap on your harness, step onto the platform, and take a deep breath as you prepare to launch into the air and zip along exhilarating zip lines suspended between towering trees and rugged terrain. Feel the wind rushing past your face as you fly through the canopy, taking in panoramic views of the surrounding landscape below. Whether you're gliding over dense forests, cascading waterfalls, or lush valleys, zip-lining offers an adrenaline-pumping experience that will leave you feeling exhilarated and alive. So join me, and let's zip through the air together on an adventure that will take your breath away!","Homestead Ziplines", new User("PeterRick","poiuhnm",R.drawable.men8,38,4.7,"\uD83D\uDE80 Tech enthusiast with a passion for innovation and a knack for problem-solving. \uD83D\uDCA1 Whether I'm coding late into the night or brainstorming the next big idea, I'm always on the cutting edge of technology. \uD83D\uDDA5️ Proud geek with a love for all things sci-fi and a collection of gadgets that would make even Tony Stark jealous. \uD83C\uDF0C When I'm not immersed in the digital realm, you can find me exploring the great outdoors or whipping up some delicious dishes in the kitchen. \uD83C\uDF73 Firm believer in the power of technology to shape a better future and make the impossible possible. Let's chat about the latest tech trends, swap coding tips, or plan our next intergalactic adventure! 405-333-5279",2),R.drawable.zipline,false,"07/27/24",2,6,10));
            productsList.add(new Product("Science Fair","Welcome to our Science Fair, a vibrant celebration of discovery and innovation that ignites the imagination and fuels the spirit of inquiry. As you enter our bustling exhibition hall, you'll find yourself immersed in a kaleidoscope of scientific wonder, where each project represents a journey of exploration and experimentation. From the intricacies of biology to the marvels of physics and beyond, our fair showcases the boundless potential of scientific inquiry. Engage with passionate participants as they present their findings, embark on interactive demonstrations, and delve into thought-provoking discussions. Amidst the buzz of excitement and the hum of intellectual curiosity, let us inspire and be inspired by the limitless possibilities of science.","Sunville Elementary",new User("TommyParker","science123",R.drawable.men10,32,4.9,"\uD83C\uDFB5 Musician with a passion for composing melodies that stir the soul. \uD83C\uDFB6 Whether it's a haunting piano piece or an upbeat guitar riff, I'm always chasing the perfect harmony. \uD83C\uDF0C Inspired by the cosmos, I find inspiration in the depths of the night sky. \uD83C\uDFB8 When I'm not lost in the rhythm, you can find me stargazing, jamming with friends, or experimenting with new recipes in the kitchen. \uD83D\uDC36 Proud goldfish parent to Bubbles, the most mesmerizing swimmer you'll ever meet! \uD83D\uDC1F Let's swap musical notes or plan our next impromptu jam session. \uD83C\uDFBC #MusicMaker #Stargazer #KitchenMaestro 405-324-4171",5),R.drawable.science,false,"08/18/24",5,10,0));
            productsList.add(new Product("Trivia Night","Welcome to our Trivia Night, where knowledge reigns supreme and fun knows no bounds. As you enter our lively venue, prepare to immerse yourself in an evening of brain-teasing challenges and friendly competition. Our experienced hosts will guide you through an array of intriguing trivia questions spanning a multitude of topics, ensuring a thrilling experience for participants of all backgrounds. But Trivia Night is more than just a test of wits; it's an opportunity to connect with friends, old and new, as you collaborate to uncover obscure facts and share in the excitement of victory. Join us for an unforgettable evening filled with laughter, camaraderie, and the thrill of triumphing over trivia.","Starbucks",new User("AlexMiller","trivia123",R.drawable.men11,27,4.7,"\uD83D\uDCDA Writer with a passion for crafting stories that resonate with the human experience. ✨ Whether it's a heartfelt romance or an epic adventure, I'm always chasing the perfect narrative. \uD83C\uDFD9️ Raised in the hustle and bustle of the city, but my imagination thrives in quiet moments of reflection. \uD83D\uDD8B️ When I'm not lost in the world of words, you can find me exploring hidden bookstores or indulging in my love for dark chocolate. \uD83D\uDCD6 Proud plant parent to Basil, the most tenacious little sprout you'll ever meet! \uD83C\uDF31 Let's share writing prompts or plan our next literary escapade. \uD83D\uDCDD #Storyteller #PlantParent #Bookworm 405123-6652",4),R.drawable.trivia,false,"08/04/24",4,8,8));
            productsList.add(new Product("Soup Kitchen","Welcome to the Soup Kitchen, where warmth and compassion await. Step into our humble space, where every bowl served is a gesture of kindness towards those in need. Savor the simple yet hearty flavors of our soups, crafted with care from the freshest ingredients available. Each spoonful not only fills the stomach but also warms the soul, reminding us of the power of generosity and empathy. But our Soup Kitchen Gathering is more than just a meal; it's a beacon of hope and solidarity. Take a seat at our communal table and engage in conversations that transcend boundaries, sharing stories and experiences that enrich us all. Together, we can create a ripple of positive change, one bowl at a time. Join us for a day filled with warmth, nourishment, and the knowledge that each bowl served brings us closer together.","Miami Soup Kitchen",new User("NathanHale","volunteer123",R.drawable.men13,29,4.8,"\uD83C\uDF99️ Podcaster with a passion for sparking meaningful conversations and exploring diverse perspectives. \uD83C\uDFA7 Whether it's a thought-provoking interview or a lighthearted discussion, I'm always chasing the perfect dialogue. \uD83C\uDF0D Driven by a curiosity about the world, I find inspiration in the stories of everyday people. \uD83D\uDCDA When I'm not recording episodes, you can find me browsing antique markets, volunteering at local shelters, or enjoying a leisurely bike ride. \uD83D\uDC31 Proud cat parent to Whiskers, the most inquisitive feline friend you'll ever meet! \uD83D\uDC3E Let's share podcasting insights or plan our next community event. \uD83C\uDFA4 #PodcastHost #CatParent #CommunityBuilder 405-547-6326",7),R.drawable.soup,false,"07/5/24",4,15,0));
            productsList.add(new Product("Hiking Trip", "Let's escape the hustle and bustle of everyday life and venture into the serene wilderness together. Feel the thrill of discovery as we traverse winding trails, surrounded by towering trees and breathtaking vistas. With each step, we'll share stories, laughter, and the joy of exploring nature's hidden treasures. Let's breathe in the crisp mountain air, listen to the symphony of birdsong, and immerse ourselves in the beauty of the great outdoors. Whether you're an experienced hiker or just starting out, there's something magical about embarking on this journey with friends by your side. So lace up your hiking boots, pack your water bottles, and join me as we embark on an unforgettable adventure into the heart of nature.", "Destin Nature Park", new User("JarenGonzales", "ihbshb@",R.drawable.men,24,4.8,"\uD83D\uDCF8 Photographer with a passion for capturing life's beautiful moments. \uD83C\uDF1F Whether it's a breathtaking landscape or candid smiles, I'm always chasing the perfect shot. \uD83D\uDCF7 Born and raised in the city but happiest when I'm exploring the great outdoors. \uD83C\uDFDE️ When I'm not behind the lens, you can find me hiking, camping, or indulging in my love for spicy food. \uD83C\uDF36️ Proud dog dad to Luna, the fluffiest adventure buddy you'll ever meet! \uD83D\uDC3E Let's swap photography tips or plan our next spontaneous road trip. \uD83D\uDE0A #Wanderlust #DogDad #AdventureSeeker 405-687-2145",8), R.drawable.park,true,"07/03/24",5,7,0));

            int temp;
        Product temp2;
        Product temp3;
//            for(int x = 0; x < productsList.size();x++){
//                temp = (int)(Math.random()* (productsList.size()-1));
//                temp2 = productsList.get(temp);
//                productsList.set(temp,productsList.get(x));
//                productsList.set(x,temp2);
//            }

            ForYouActivity.setFirst(false);
        }

        ProductAdapter adapter = new ProductAdapter(this);
        adapter.setProducts(productsList);
        products.setAdapter(adapter);
        products.setLayoutManager(new GridLayoutManager(this,2));


    }
    public void openMainActivity(){

        Intent intent = new Intent(this, MainActivity2.class);
        this.startActivity(intent);
    }
    public void openInboxActivity(){

        Intent intent = new Intent(this, InboxActivity.class);
        this.startActivity(intent);
    }
    public void openProfileActivity(){

        Intent intent = new Intent(this, ProfileActivity.class);
        this.startActivity(intent);
    }
    public void openForYouActivity(){

        Intent intent = new Intent(this, ForYouActivity.class);
        this.startActivity(intent);
    }
    public void openFollowingActivity(){

        Intent intent = new Intent(this, FollowingActivity.class);
        this.startActivity(intent);
    }

    public void openCalenderActivity(){

        Intent intent = new Intent(this, CalenderActivity.class);
        this.startActivity(intent);
    }

    public void openSearchActivity(){

        Intent intent = new Intent(this, SearchActivity.class);
        this.startActivity(intent);
    }
    public void openUserPage(){
        Intent intent = new Intent(getApplicationContext(), UserPage.class);
        getApplicationContext().startActivity(intent);
    }
    public static Product findProduct(String name){

        for(int x = 0; x < productsList.size();x++){
            if(productsList.get(x).getProductName().equals(name)){
                return productsList.get(x);
            }
        }
        return null;
    }
    public static boolean findProductInForYouBoolean(String name, String image){

        for(int x = 0; x < ForYouActivity.getForYouList().size();x++){
            if(ForYouActivity.getForYouList().get(x).getProductName().equals(name) && ForYouActivity.getForYouList().get(x).getProductImageURL().equals(image)){
                return true;
            }
        }
        return false;
    }
    public static boolean findProductInFollowingBoolean(String name, String image){

        for(int x = 0; x < FollowingActivity.getFollowingProductList().size();x++){
            if(FollowingActivity.getFollowingProductList().get(x).getProductName().equals(name) && FollowingActivity.getFollowingProductList().get(x).getProductImageURL().equals(image)){
                return true;
            }
        }
        return false;
    }
    public static ArrayList<Product> getProductsList(){
        return productsList;
    }

    public static void addToProdList(Product forNow){
        productsList.add(forNow);
    }


}